### PR TITLE
Leetcode question added

### PR DESCRIPTION
**Pull request by titichhm**
Medium level leetcode question. Question link in read-me file, along with C++ solution and description.

### CODE REVIEW

**Review by Vishruth-S — APPROVED** [review]
👍 👍

**Comment by Vishruth-S** [comment]
`Question` file should have been of `.md` format. This time its okay I will merge but please take care in future contributions.

**Comment by titichhm** [comment]
@Vishruth-S Sure. Actually this was my first time so I didn't know. Thanks for letting me know :)

**Comment by Vishruth-S** [comment]
Its mentioned in the [contributing.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) 🙃

**Comment by titichhm** [comment]
Yeah, sorry I forgot to notice :(

**Pull request merged**
