### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ArjunBhandari-666**
Hey there!, Thanks for submitting a PR to this repo :smiley:  
Please complete the following checklist for your PR to be approved. Mark the items by adding an `x`.   
Example:  - [ ] Mark me as completed  
To mark: - [x] Mark me as completed

- [x] My Pull Request adheres to the Contribution guidelines.
- [x] I have added `problem.md` and `solution` files in the appropriate folder
- [x] In `problem.md` I have provided a correct link to the problem.  
  (In case you are not adding a problem, you can freely mark this as complete)
- [x] My solution passes all the testcases within the given constraints.
- [x] I have properly indented and documented my solution using comments.

If any of the above is unmarked, please make the necessary changes and then mark them so that you're PR can be approved and merged.  
(Only completed checklist PRs will be reviewed)

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Please add comments explaining `Armstrong Number Problem` and `The One with the Fibonacci`

Also note that you can make the changes and push them to the same PR. You don't have to create a new PR each time you make a change

**Comment by ArjunBhandari-666** [comment]
I have updated it with comments in solutions. Could you please reconsider these?

**Comment by Vishruth-S** [comment]
@ArjunBhandari-666  Yeah now it looks good 👍 . 
Also I'm really sorry I forgot to mention this earlier, could you please move this `Math and strings problems` folder into the `Misc` folder since the main folders are only for problems from their respective websites 😅

**Comment by ArjunBhandari-666** [comment]
Yes sure, hold up!

**Comment by ArjunBhandari-666** [comment]
I'm new to GitHub and I'm using a super old lappy, with Intel atom rn, so I can't clone a repo and I can't delete files in the web interface

Pardon me, but I'll be issuing a new PR

Please ignore all the old ones, I'm sorry!

**Comment by Vishruth-S** [comment]
@ArjunBhandari-666  That's alright, no worries 😄. I have merged your PR #429  👍 
Closing this.

**Pull request closed without merging**
