### PR TITLE
Add solution to POSAND problem Oct-challange

### PR DESCRIPTION
**Pull request by Zaidtech**
@Vishruth-S  i made a PR, kindy review the same.

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Please add comments to your solution explaining the logic used.
This is *clearly* mentioned [here](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md#important-note-read-this-before-sending-a-pull-request)

**Comment by Zaidtech** [comment]
Ah!! @Vishruth-S ,  Sure will be commenting the code..

**Comment by Vishruth-S** [comment]
@Zaidtech  Alright. Please leave a reply here once you make the changes so that I can review 😃

**Comment by Zaidtech** [comment]
@Vishruth-S kindly review the changes !! 
Moreover is this repo under HacktoberFest :smile:

**Review by Vishruth-S — APPROVED** [review]
Looks great now 👍 Thanks for your contribution 😄

**Comment by Zaidtech** [comment]
Thanks a lot! :smiley:

**Comment by Vishruth-S** [comment]
@Zaidtech Welcome 😄 . Also do star this repo if you haven't already 🙃

**Comment by Zaidtech** [comment]
@Vishruth-S, if this repo comes under Hactoberfest can you please mark the PR as hactoberfest-accepted

**Comment by Vishruth-S** [comment]
@Zaidtech  The `hacktoberfest-accepted` label is only needed if this repo is not having the `hacktoberfest` Topic or I am not approving/merging your PR. 
Since your PR was approved and merged in a hacktoberfest Topic Repo, it will be counted, no worries 😃 .
Source: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by Zaidtech** [comment]
Ah!! but I read the terms and the pr are not counted until they are labeled as hactoberfest-accepted  !! even one of my colleague has made his 4- PR's fail this way!! :sweat_smile:

**Comment by Vishruth-S** [comment]
I think you have been misguided. The link I sent you is the official hacktoberfest website and the guidelines given there are original and the correct ones.🙃
And this PR will definitely be counted if you have registered there 😃

**Comment by Zaidtech** [comment]
ohk!! thanks a lot  @Vishruth-S :smile:

**Pull request merged**
