### PR TITLE
Added a Dymanic Programming for Knapsack Problem

### PR DESCRIPTION
**Pull request by anandmohan4143**

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Please add 1-2 example testcases with input and output in `problem.md`

**Comment by anandmohan4143** [comment]
i have pulled a request with the changes made. Kindly look into it.

**Comment by anandmohan4143** [comment]
Please refer the pull request #308

**Comment by Vishruth-S** [comment]
@anandmohan4143  Please check #308 and make the changes requested there. Closing this.

**Pull request closed without merging**
