### PR TITLE
ELEVTR problem solution is added from codechef

### PR DESCRIPTION
**Pull request by SwagataSrimani**
Hey! I have added ELEVTR problem solution of CodeChef here. Please accept my PR  and help me to contribute in open source.

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Could you please add some comments in your solution briefly explaining the logic used.
This is mentioned in [Contributing](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md#important-note-read-this-before-sending-a-pull-request) guidelines.

**Comment by SwagataSrimani** [comment]
Sure. I will check .

**Comment by SwagataSrimani** [comment]
Please check it now if it is OK or not.

**Comment by Vishruth-S** [comment]
@SwagataSrimani  Umm I don't see any changes 😅 . Please check if you have pushed your changes...

**Review by Vishruth-S — APPROVED** [review]
Awesome 👍 Thanks for contributing 😄

**Comment by SwagataSrimani** [comment]
Thank you so much.

**Pull request merged**
