### PR TITLE
Uploaded solution for problem number 83 of leetcode i.e Remove Duplicates from Sorted List

### PR DESCRIPTION
**Pull request by tanmoyee04**

### CODE REVIEW

**Review by Vishruth-S — COMMENTED** [review]
This has 54 file changes instead of 2.
Please fork the repo again and send another PR.

**Comment by tanmoyee04** [comment]
I am unable to send another PR . Whenever I am sending a second PR , it's
showing " view pull request " . I donno what to do. I am a beginner in open
source. Can you please kindly help

**Comment by Vishruth-S** [comment]
@tanmoyee04  Will look into this issue and get back to you as soon as I can.

**Comment by Vishruth-S** [comment]
Already merged this in  #83  
Closing this

**Pull request closed without merging**
