### PR TITLE
COVID RUN CodeChef

### PR DESCRIPTION
**Pull request by sourceganesh**
The pull request contains the solution to October Challenge CovidRun in C++ language

### CODE REVIEW

**Review by Vishruth-S — APPROVED** [review]

**Comment by Vishruth-S** [comment]
The solution seems blank...Were you planning on adding only the problem?
If no, then please add the solution. Separate PRs for solution and problem will not be encouraged.

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
The solution seems blank...Were you planning on adding only the problem?
If no, then please add the solution. Separate PRs for solution and problem will not be encouraged.
if you only wanted to add the problem, then reply to this with 👍  and I will merge

**Comment by sourceganesh** [comment]
> The solution seems blank...Were you planning on adding only the problem?
> If no, then please add the solution. Separate PRs for solution and problem will not be encouraged.
> if you only wanted to add the problem, then reply to this with 👍 and I will merge

Added the solution and logic, guess i forgot mb

**Review by Vishruth-S — APPROVED** [review]
👍

**Pull request merged**
