### PR TITLE
Chef and Card Game

### PR DESCRIPTION
**Pull request by Skub123**
Added New Folder

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Is this from codechef? If yes, add it to Codechef folder.
Otherwise add it to misc folder.
Also please add comments in your code explaining the logic used.

**Comment by Skub123** [comment]
Yes its codechef long challenge problem problem

**Comment by Vishruth-S** [comment]
@Skub123  Then please add it in the CodeChef_problems folder.
Also add comments to your solution explaining the logic used.

**Comment by Vishruth-S** [comment]
This PR will be closed soon if there is no response.

**Comment by Skub123** [comment]
Yes I add immediately

**Pull request closed without merging**
