### PR TITLE
Added FizzBuzz HackerRank problem and solution in python

### PR DESCRIPTION
**Pull request by ajaysalunkhe16**

### CODE REVIEW

**Comment by ajaysalunkhe16** [comment]
@Vishruth-S  Can you please take a look at PR?

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Please provide a brief explanation/logic for your code.
(Can be in the form of comments along with code or add logic at the top)

**Comment by ajaysalunkhe16** [comment]
> Please provide a brief explanation/logic for your code.
> (Can be in the form of comments along with code or add logic at the top)

@Vishruth-S I have added comments please take a look.

**Review by Vishruth-S — APPROVED** [review]
👍

**Pull request merged**
