### PR TITLE
Adding Leetcode solutions

### PR DESCRIPTION
**Pull request by lusmoura**

### CODE REVIEW

**Review by AzadKshitij — CHANGES_REQUESTED** [review]
Plese add logic of your code in form of comment

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
@AzadKshitij  Thanks for pointing out.
@lusmoura  Please make the necessary changes and ensure that your PR follows all guidelines mentioned [here](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md#important-note-read-this-before-sending-a-pull-request)

**Comment by lusmoura** [comment]
Sorry about that. I added the logic and some test cases, ans I hope it all makes sense.

**Review by Vishruth-S — APPROVED** [review]
Awesome 👍  Thanks for your contribution 😃

**Pull request merged**
