### PR TITLE
Added another problem

### PR DESCRIPTION
**Pull request by amul-agrawal**
Bfs based problem.

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
The Grid problem has already been added and merged in #265 .
Please remove the duplicate

**Comment by amul-agrawal** [comment]
@Vishruth-S Made the required changes.

**Review by Vishruth-S — APPROVED** [review]
Good work 👍 Thanks for contributing 😄

**Comment by Vishruth-S** [comment]
@amul-agrawal  Oops. I think you deleted the Grid problem itself. I just meant to delete it from this commit. Shall I revert this PR ?, or could you send another one to add that back ?

**Pull request merged**
