### PR TITLE
Hackerrank | Sherlock and valid strings.

### PR DESCRIPTION
**Pull request by div-bargali**
Add sherlock and valid strings solution.

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Please provide a brief explanation/logic to your solution.
It can either be in the form of comments along with the code or add logic at the beginning

**Comment by Vishruth-S** [comment]
@div-bargali  This PR will be closed if the requested changes are not made soon

**Comment by div-bargali** [comment]
I will make the changes by the end of the day.

**Comment by Vishruth-S** [comment]
@div-bargali  Alright. Leave a message here once you have finished the same

**Comment by div-bargali** [comment]
@Vishruth-S Made the required changes. Please review!

**Review by Vishruth-S — APPROVED** [review]
Good job 👍

**Pull request merged**
