### PR TITLE
Added Insert Interval in Java

### PR DESCRIPTION
**Pull request by mihirsood**

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Please make the following changes

* Add comments to your solution **explaining** the logic used
* Add link to the problem in a file named `problem.md`

These are *clearly* mentioned  [here](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md)

**Comment by mihirsood** [comment]
I have made some changes. Please review them. Thankyou.

**Comment by Vishruth-S** [comment]
@mihirsood  It still seems the same. There are no comments in your solution and there is no `problem.md` file.
Please recheck

**Comment by Vishruth-S** [comment]
@mihirsood Sorry I didn't notice that the file already existed. 
Also, I know the code may be self explanatory. But I am insisting on adding comments for the following reasons
* Even a beginner level person should be able to see and understand the logic involved.
* Since this repo is participating in hacktoberfest, these guidelines are imposed so that we can reduce spam PRs and approve only those having genuine contributions. Hence it is advised that you add comments so that people are discouraged from simply copy-pasting code.

Hope these are clear and understandable.

**Pull request closed without merging**
