### PR TITLE
adding new codeforces problem

### PR DESCRIPTION
**Pull request by MariamFahmy98**
I have added a new greedy problem from codeforces, I have implemented it in c++ and discussed its logic idea, could you please check it?
thanks in advance

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Could you please delete the unnecessary `code_problems` file

**Comment by MariamFahmy98** [comment]
I have created a folder for the problem name and inside it, there is 2 files one for problem.md and other for solution.cpp, Do you mean deleting extra files from the whole repo in general?

**Comment by MariamFahmy98** [comment]
I have made it by mistake, sorry.
I have delete it, could you please check it?

**Review by Vishruth-S — APPROVED** [review]
Good work 👍

**Pull request merged**
