### PR TITLE
add new problem

### PR DESCRIPTION
**Pull request by mo1sharnoby**
I have added a new problem from codeforces and I implemented it using cpp and discussed its logic idea, could you please check it?
thanks in advance!

### CODE REVIEW

**Comment by Vishruth-S** [comment]
@mo1sharnoby  I don't see any new additions to the code. Could you please recheck.
Also please don't change the default [Pull Request Template](https://github.com/Vishruth-S/CompetitiveCode/blob/main/PULL_REQUEST_TEMPLATE.md). Send another PR with the automatically generated PR template and complete the checkboxes in order for your PR to reviewed.

**Comment by mo1sharnoby** [comment]
sorry I have made a mistake , I will fix it and make a new pull request

**Comment by mo1sharnoby** [comment]
I fixed it could you check it again, thanks in advance

**Comment by Vishruth-S** [comment]
@mo1sharnoby  I still don't see any changes. Also please send a new Pull Request with the default template. (It automatically appears when you click on new pull request). Refer some recently merged PRs to see what I mean. If you still have doubts, leave a reply here.

**Pull request closed without merging**
