### PR TITLE
Create checkprime.py

### PR DESCRIPTION
**Pull request by Darshan15071998**
Used for checking whether a given No. is Prime or Not.

### CODE REVIEW

**Review by Vishruth-S — COMMENTED** [review]
If you are creating a new problem, it MUST be in the misc folder with appropriate file names for problem and solution. 
Please refer [Contributing.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/Contributing.md) before sending a PR

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Please refer contributing.md and make the changes accordingly.

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Add comments to your code **explaining** the logic used.
This is clearly mentioned [here](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md#important-note-read-this-before-sending-a-pull-request)

**Review by Darshan15071998 — COMMENTED** [review]
Added explanation in the form of comments into every solution

**Comment by Vishruth-S** [comment]
Duplicate of #168 . Closing this.

**Pull request closed without merging**
