### PR TITLE
added a problem

### PR DESCRIPTION
**Pull request by neha07kumari**

### CODE REVIEW

**Comment by neha07kumari** [comment]
#289  Please check it . @Vishruth-S

**Review by Vishruth-S — APPROVED** [review]
Good job 👍 Thanks for your contribution 😄 
Also, In the future, it would be better if you could add problems of higher difficulty since this problem was a bit too trivial.😅

**Comment by Vishruth-S** [comment]
Oh and you can ignore the "check failed" thing. It's a new feature which is still being tested. It's having some issues which I am looking to solve asap

**Comment by neha07kumari** [comment]
Thankyou. Sure I'll add it as soon as possible .😁

**Pull request merged**
