### PR TITLE
Added Cses problems

### PR DESCRIPTION
**Pull request by SeekerHub**
Added Ferris Wheel problem from CSES.
happy to contribute!

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Please make the following changes
* Create a file named `problem.md` and add the link to the problem
* Add comments to your solution **explaining** the logic used.

These are *clearly* mentioned [here](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md#important-note-read-this-before-sending-a-pull-request)

**Comment by SeekerHub** [comment]
Ohkay i will  make it

**Comment by SeekerHub** [comment]
I have made the necessary changes for ease of understanding.
Thanks for the suggestion.

**Comment by Vishruth-S** [comment]
@SeekerHub  Please add the Logic/Approach as comments in your `solution` file and NOT in `problem` file.
This is also *clearly* mentioned [here](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md#important-note-read-this-before-sending-a-pull-request)

(We are trying to make this repo as uniform as possible. Hence it is necessary to follow all the guidelines. Hope you understand)

**Comment by SeekerHub** [comment]
Sorry for the inconvenience.
Thanks

**Review by Vishruth-S — APPROVED** [review]
Good job 👍 Thanks for your contribution 😄

**Pull request merged**
