### PR TITLE
Added Geeksforgeeks problem and solution about palindrome linked list

### PR DESCRIPTION
**Pull request by Ankita1811**

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
@Ankita1811  Could you please add some comments to your solution explaining the logic used ..

**Comment by Ankita1811** [comment]
@Vishruth-S I found the mid point of the linked list, then reversed the second half of the linked list. Finally I compared the first half and the second half of the linked list to check if they are same. If same, the linked list is palindrome.

**Comment by Ankita1811** [comment]
I will also add the comments to the solution.

**Comment by Vishruth-S** [comment]
@Ankita1811  You don't have to send another PR. You can make the changes and push your commits to this same PR..

**Comment by Ankita1811** [comment]
@Vishruth-S I have pushed the changes and have commented the code. Can you please look into it

**Review by Vishruth-S — APPROVED** [review]
Good work 👍 Thanks for your contribution 😄

**Pull request merged**
