### PR TITLE
Added the HackerRank problem and its solution in Python

### PR DESCRIPTION
**Pull request by Aashrut**
Added the HackerRank problem and its solution in Python. It passed all the test cases on HackerRank.

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Please add the logic used to your `solution` file in the form of comments

**Comment by Aashrut** [comment]
Please, check it. I have updated the solution.py and added the logic required for the program.

**Review by Aashrut — COMMENTED** [review]
Can you check this? If you have any other suggestion then, please, tell me.

**Review by Vishruth-S — APPROVED** [review]
👍

**Pull request merged**
