### PR TITLE
New

### PR DESCRIPTION
**Pull request by dikshajoshi18**

### CODE REVIEW

**Review by Vishruth-S — APPROVED** [review]
This looks great 👍 
#267 seems to be a duplicate of this.
Can I merge this and close #267 ?

**Comment by dikshajoshi18** [comment]
yes sure

**Comment by dikshajoshi18** [comment]
no #267 is one question and #268 is another question

**Comment by dikshajoshi18** [comment]
ou need to merge both

**Comment by Vishruth-S** [comment]
@dikshajoshi18  #267 is `police recruits` question and solution.
The same is there in this PR also.

**Comment by dikshajoshi18** [comment]
ok
merge anyone

**Comment by Vishruth-S** [comment]
Ok. Merging this.

**Pull request merged**
