### PR TITLE
Added solution for Maximum Product Subarray - Leetcode - Python

### PR DESCRIPTION
**Pull request by GSNCodes**
Added the solution in python for the Problem Leetcode - 152: Maximum Product Subarray
Difficulty: Medium

@Vishruth-S
Kindly take a look at my PR. I have adhered to the specified guidelines in Contributing.md. 😄

### CODE REVIEW

**Comment by GSNCodes** [comment]
@Vishruth-S 
Also, please do add the octoberfest label to this pull requet :)

**Review by Vishruth-S — APPROVED** [review]
Good work 👍 😄

**Comment by Vishruth-S** [comment]
@GSNCodes  That label is needed only if I am not approving/merging your PR. Since I have approved and merged your PR, it is considered as hacktoberfest-accepted and will be counted 😃 . Reference: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by GSNCodes** [comment]
@Vishruth-S  Got it ! Thank you 👍

**Pull request merged**
