### PR TITLE
Leetcode questions added

### PR DESCRIPTION
**Pull request by shrey1608**

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Could you please add more comments to your solution briefly explaining the approach used.

**Comment by shrey1608** [comment]
@Vishruth-S I have done the needful changes please merge it :)

**Comment by Vishruth-S** [comment]
@shrey1608  I don't see any significant changes from the previous commit. The reason I am insisting on adding comments is because -
* It would be really useful for beginners and those new to CP
* Since this repo is participating in hacktoberfest, these guidelines are imposed so as to discourage people from simply copy-pasting code and sending spam PRs.

Hope you understand 😅 
Kindly add more comments just briefly explaining the approach used. Leave a reply here once you have done the same.
Will review and merge.

**Comment by shrey1608** [comment]
@Vishruth-S I have added more explanation to each problem in the problem first-bad-version i can explain more as we just have to perform binary search nothing else. Please merge it Thanks!

**Review by Vishruth-S — APPROVED** [review]
Good work 👍 Thanks for your contribution 😄

**Pull request merged**
