### PR TITLE
A Problem on Sticks-Solution

### PR DESCRIPTION
**Pull request by shruti01052002**

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Please add logic used in the form of comments
Refer [this](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) before sending a PR

**Comment by Vishruth-S** [comment]
This PR will be closed soon if the requested changes are not made

**Comment by shruti01052002** [comment]
I"ll surely do the changes by tonight. please don't close the pull requests.

**Comment by Vishruth-S** [comment]
@shruti01052002  Alright take your time. Just leave a reply here once you are done so that I can review 😃

**Comment by shruti01052002** [comment]
I have done the required changes please review it and let me know if any
changes need to be done.😃😃

**Review by Vishruth-S — APPROVED** [review]
Good job 👍 Thanks for your contribution 😃 
Also do star this repo if you found it useful 🙃

**Comment by shruti01052002** [comment]
I have already starred the repo 🤘🤩

**Pull request merged**
