### PR TITLE
solution.py

### PR DESCRIPTION
**Pull request by Darshan15071998**

### CODE REVIEW

**Review by AzadKshitij — CHANGES_REQUESTED** [review]
Plese add logic of your code add comment

**Review by Darshan15071998 — COMMENTED** [review]
I have changed the code by adding explanations in the form of Comments into my Code

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Add the `problem.md` file from #160 . Sending separate PRs for problem and solution is not encouraged.

**Comment by Darshan15071998** [comment]
Sir, I have No Idea about how to add a file to the existing one can you please give me some hint about how to add problem.md file #160 here

**Comment by Vishruth-S** [comment]
Alright since you are a beginner, Its alright I will merge both PRs...
But in the future, please add both of them and then only send a PR

**Review by Vishruth-S — APPROVED** [review]

**Comment by Darshan15071998** [comment]
Okay, Thank you so much Vishruth Sir :)

**Comment by Vishruth-S** [comment]
@Darshan15071998  Welcome 😄 . Do show your support by starring this repo 🙃

**Pull request merged**
