### PR TITLE
"Nice Matrix" Codeforces problem

### PR DESCRIPTION
**Pull request by babitha667**
I have written cpp code for Nice Matrix

### CODE REVIEW

**Comment by babitha667** [comment]
@Vishruth-S  please check my work

**Review by Vishruth-S — APPROVED** [review]
Good work 👍 😃 
Please star ⭐ this repo to support 🙃

**Comment by babitha667** [comment]
sure :)

**Comment by babitha667** [comment]
@Vishruth-S  shall I add some more questions and my solutions for good questions from Codeforces , codechef . please assign me .

**Pull request merged**
