### PR TITLE
Added InterviewBit Problem from maths section

### PR DESCRIPTION
**Pull request by bplm**
Hey there!, Thanks for submitting a PR to this repo :smiley:  
Please complete the following checklist for your PR to be approved. Mark the items by adding an `x`.   
Example:  - [ ] Mark me as completed  
To mark: - [x] Mark me as completed

- [x ] My Pull Request adheres to the Contribution guidelines.
- [ x] I have added `problem.md` and `solution` files in the appropriate folder
- [ x] In `problem.md` I have provided a correct link to the problem.  
  (In case you are not adding a problem, you can freely mark this as complete)
- [x ] My solution passes all the testcases within the given constraints.
- [ x] I have properly indented and documented my solution using comments.

If any of the above is unmarked, please make the necessary changes and then mark them so that you're PR can be approved and merged.  
(Only completed checklist PRs will be reviewed)

### CODE REVIEW

**Comment by bplm** [comment]
Please check the IB solution contributed to from maths section.If appropriate , I shall add more efficient and proper soltions asked in many interviews.

**Comment by bplm** [comment]
> @bplm I don't see any code added, could you please check again ?

Sorry for the mistake.Can you please check the code now?
If appropriate , I have othe solutions for complex problems as well which I can contribute to.

**Comment by Vishruth-S** [comment]
@bplm  Please add a link to the problem in the `problem.md` file. Currently it is empty

**Comment by bplm** [comment]
> @bplm Please add a link to the problem in the `problem.md` file. Currently it is empty

@Vishruth-S  I am sorry again! I hope its there now.

**Review by Vishruth-S — APPROVED** [review]
Good job 👍 
Do star ⭐ this repo if you haven't already 🙃

**Pull request merged**
