### PR TITLE
codechef_problem (A Problem on Sticks )solution 

### PR DESCRIPTION
**Pull request by neha0123**

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
`A problem on sticks` already exists in the codechef_problems folder.
Remove `problem.md` and add your `solution` to that folder.

**Comment by neha0123** [comment]
Done changes please review it

**Review by Vishruth-S — APPROVED** [review]

**Comment by Vishruth-S** [comment]
It is still not inside  `A problem on sticks` folder. Anyway I will do that from my end after merging 👍

**Comment by nehu04** [comment]
👍

**Pull request merged**
