### PR TITLE
Hotel price

### PR DESCRIPTION
**Pull request by ficolian**
hello sir @Vishruth-S , I would like to add new hackerRank solution for Algorithm Hotel Price Problem here.
image
Please kindly check my work Sir 
Thank you😁

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Please add more comments to your solutions explaining the logic used.

**Comment by ficolian** [comment]
Okay Sir
I have fixed it
Thank you 🙏

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Could you please check your solution again.
For the testcase,
```
2
standard 3 1
apartment 1 1
```
Your code's output is `400`
Expected output: `500`

**Comment by ficolian** [comment]
The tes ouput is already 500 sir 
image

**Review by Vishruth-S — APPROVED** [review]

**Comment by ficolian** [comment]
Thank you Sir 😬😬

**Pull request merged**
