### PR TITLE
bowler  solution added

### PR DESCRIPTION
**Pull request by rijusougata13**

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Add comments to your solution explaining the logic used.
This is clearly mentioned [here](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md#important-note-read-this-before-sending-a-pr)

**Comment by Vishruth-S** [comment]
This PR will be closed soon if there is no response

**Comment by rijusougata13** [comment]
i have added comments and instruction

**Comment by Vishruth-S** [comment]
Could you please recheck your `bowler` solution.
The output of your code for the testcase 
```
2
4 3 2
5 4 1
```
is 
```
3 2 1 3 
-1
```
Expected Output 
```
1 2 3 2
-1
```

**Comment by Vishruth-S** [comment]
Also add comments to the `chef and work` solution as well.

**Pull request closed without merging**
