### PR TITLE
hackerrank pattern

### PR DESCRIPTION
**Pull request by malyabansalper**
This is my first pull request please accept it 
it is a simple hacker rank program to print hacker rank pattern the "H" pattern.

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
This should not be in the "Apple and oranges" folder. It must be in it's own separate folder inside hackerrank_problems.
Please refer [Contributing.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/Contributing.md)

**Review by malyabansalper — COMMENTED** [review]
okay sir I will surely do it kindly please approve it for now

**Comment by malyabansalper** [comment]
I have done it please look at it and approve

**Comment by malyabansalper** [comment]
Please kindly review the change sir .This is my first contribution so I kindly request you to ignore the mistakes in the work and guide me through and help me by accepting it.Thank you.

**Review by Vishruth-S — COMMENTED** [review]
Sure I will accept it, But please make the following changes
Change `"H"` to `H` in your filename. Having unsupported characters (") in filenames can cause errors when  cloning on windows devices.

**Comment by malyabansalper** [comment]
Done kindly please check if its okay now. thank you .

**Comment by Vishruth-S** [comment]
Could you please delete the remaining files. They are still having the (") in the filename .
Only the `H pattern/problem.md` and `H pattern/solution` files are needed.

**Comment by malyabansalper** [comment]
done

**Comment by Vishruth-S** [comment]
@malyabansalper  Delete ` Hackerrank_problems/Hackerrank pattern"H"/Problem.md ` and `Hackerrank_problems/Hackerrank pattern"H"/main.py `

**Comment by malyabansalper** [comment]
i have deleted it kindly refresh and check again please

**Review by Vishruth-S — APPROVED** [review]
Apparently they hadn't been deleted. I have deleted them from my end.
Now it looks fine 👍

**Comment by malyabansalper** [comment]
okay thanks a lot actually I couldn't exactly figure out how to delete but
thanks a lot for the help.

**Pull request merged**
