### PR TITLE
Even Odds

### PR DESCRIPTION
**Pull request by josefnagy1999**
Being a nonconformist, Volodya is displeased with the current state of things, particularly with the order of natural numbers (natural number is positive integer number). He is determined to rearrange them. But there are too many natural numbers, so Volodya decided to start with the first n. He writes down the following sequence of numbers: firstly all odd integers from 1 to n (in ascending order), then all even integers from 1 to n (also in ascending order). Help our hero to find out which number will stand at the position number k.

### CODE REVIEW

**Comment by Vishruth-S** [comment]
@josefnagy1999  I will check this PR soon. This is just to inform that you can ignore the "check failed" thing. It is a new feature which is still being tested and has some issues.

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Please add comments to your solution explaining the logic used.
This is *clearly* mentioned in the [Contributing](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) guidelines

**Review by josefnagy1999 — COMMENTED** [review]
Added Description

**Comment by josefnagy1999** [comment]
Is it good now?

**Review by Vishruth-S — APPROVED** [review]
Good work 👍
Do give this repo a ⭐ if you haven't already 🙃

**Pull request merged**
