### PR TITLE
HEAP SORT using JAVA

### PR DESCRIPTION
**Pull request by sayan2044**

### CODE REVIEW

**Comment by sayan2044** [comment]
only heap sort program is given all others are deleted

**Review by Vishruth-S — COMMENTED** [review]
Please read [Contributing.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) before sending PRs.

It is clearly given that you must create folder which must contain `problem` and `solution`. Please go through it again and ensure you adhere to all guidelines given there.

**Comment by sayan2044** [comment]
> Please read [Contributing.md](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md) before sending PRs.
> 
> It is clearly given that you must create folder which must contain `problem` and `solution`. Please go through it again and ensure you adhere to all guidelines given there.

can I do the pr again?
with your permission

**Comment by sayan2044** [comment]
I closed it by mistake sorry

**Comment by Vishruth-S** [comment]
@sayan2044  No problem. Please make the necessary changes in this PR or close this and send a new one

**Pull request closed without merging**
