### PR TITLE
add python solution for sequence equation

### PR DESCRIPTION
**Pull request by vivax3794**

### CODE REVIEW

**Comment by vivax3794** [comment]
relevant issue: #16

**Comment by vivax3794** [comment]
relevant issue: #30

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Please add a bit of explanation/logic to your solution.
It can be either in the form of comments along with the code or add logic at the beginning.
(Refer last part of contributing.md)

**Comment by vivax3794** [comment]
oh I thought this might have been enough as the problem is not that complex, 
```python
# get the index of the index of x.
results.append(p.index(p.index(x) + 1) + 1)
```

but sure I will add more. give me a minite

**Comment by vivax3794** [comment]
there, is that better @Vishruth-S ?

**Review by Vishruth-S — APPROVED** [review]
That's better👍 The reason I asked to give explanations is because
 1. It can be understood even by a beginner 
 2. Otherwise, people may simply copy and paste code so that they can make a PR, which is not adhering to the idea of this repo.

So thank you for your contribution :). Appreciate it 👍

**Pull request merged**
