### PR TITLE
Added a CodeChef problem!

### PR DESCRIPTION
**Pull request by ananya0504**
Please do check and merge!

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Please provide a brief explanation/logic to your solution.
It can either be in the form of comments along with the code or add logic at the beginning

**Comment by ananya0504** [comment]
Okay so I will add the logic, please guide me once if I will have to again fork the repo or what? How should I go about it for the changes?

**Comment by Vishruth-S** [comment]
@ananya0504  No need to fork again. You can work on your existing fork. Just modify your code and commit your changes.  
If you face any more issues, feel free to ask :)

**Comment by ananya0504** [comment]
Okay so I have commited the changes, added the comments. Now but after committing it did not show me options to make a PR again!

**Comment by Vishruth-S** [comment]
@ananya0504  No you needn't have to send another PR. You just made you changes and by commiting them, you updated it here itself. I can see them and they're good now :)

**Review by Vishruth-S — APPROVED** [review]
Good Job 👍 :)

**Comment by ananya0504** [comment]
Wont you label it as hacktober fest accepted?

**Comment by Vishruth-S** [comment]
@ananya0504  That label is needed only if I am not approving/merging your changes. Since I approved and merged them, it is considered as Hacktoberfest accepted and will be counted.  Reference: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Pull request merged**
