### PR TITLE
credit card problem stable working

### PR DESCRIPTION
**Pull request by sourceganesh**
This PR contains the code for the credit card validity check program from Hackerrank

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Add comments to your code explaining the logic used,
Refer [this](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md#important-note-read-this-before-sending-a-pr)

**Comment by sourceganesh** [comment]
Logic has been added for the programs do check them out

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
The comments seem trivial. Please add some explanation.

**Comment by sourceganesh** [comment]
updated the  PR

**Review by Vishruth-S — APPROVED** [review]
👍

**Pull request merged**
