### PR TITLE
Created sparse_matrix file

### PR DESCRIPTION
**Pull request by Mitali-laroia**
Added solution to sparse matrix multiplication in c inside Sparse Matrix multiplication folder.
All logic used in the program have been commented properly step to step inside program.

### CODE REVIEW

**Review by Vishruth-S — COMMENTED** [review]
Could you please check your logic again with the testcases. I don't think the output is exactly correct

Here is the ouput of your code for example 0
```
0 1 1 1 2
1 0 1 2 1
3 4 22 16 9
```

The values seem different from the ones expected. The expected output as per your code should be
```
0 1 1 1 2
1 0 1 2 1
3 4 10 16 9
```

**Comment by Mitali-laroia** [comment]
@Vishruth-S can you give me the exact information about the test case like either the triplet of both the matrix or matrix itself?
I'll surely change the logic and errors .

**Comment by Vishruth-S** [comment]
@Mitali-laroia  The testcases are given [here](https://github.com/Vishruth-S/CompetitiveCode/blob/main/Misc/SparseMatrix_Multiplication/problem.md#example-0). 
Could you please verify if you are getting the same output as expected ?

**Comment by Mitali-laroia** [comment]
@Vishruth-S  Yes, I caught some errors like transposing a matrix cause some errors, so with all analysis I shifted my code in java where the approach is to multiply on when we encounter non zero element and skip for the other, checked for all test cases and approach is also commented out in the code. If any modifications are needed you can tell me :)

**Comment by Vishruth-S** [comment]
@Mitali-laroia  Actually it says in the problem constraints that "direct multiplication of matrices is not allowed". Hence, you will have to necessarily convert the matrices into their triple form and then find the product using that. 😅 
I think you did follow this in your previous commit (in C) but encountered some bugs.
Please see if you can fix your code or write new code to achieve this.

In the meantime, I will also go through your earlier submitted C code and see if I can fix the bugs 😃

**Comment by Mitali-laroia** [comment]
@Vishruth-S No, problem I have added my old solution, I remember such type of shortcomings are with triplet representation, I'll work on this solution itself and try to make it accurate :)

**Comment by Vishruth-S** [comment]
@Mitali-laroia  Ok sure 👍 . Just leave a reply here once you finish it or if you are face any issues 😄

**Pull request closed without merging**
