### PR TITLE
Add monotonic function

### PR DESCRIPTION
**Pull request by theja-vanka**

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Could you please add a brief explanation to the example so that we follow the pattern of questions followed in CP 😅

**Comment by theja-vanka** [comment]
Hey kindly check and let me know if that works.

**Review by Vishruth-S — APPROVED** [review]
Thanks for contributing 😄 
I have formatted the problem and made the headings etc more clear. Hope you are okay with that.
Will merge if you are fine with the changes 🙃 
Or if you want to make any more changes, reply here

**Comment by theja-vanka** [comment]
Hey fine by me. Go ahead and push the code. Thanks alot of allowing me to contribute.

**Comment by Vishruth-S** [comment]
@theja-vanka  Okay 😄 . 
Also do star this repo if you haven't already 🙃

**Pull request merged**
