### PR TITLE
Changes made as per requested

### PR DESCRIPTION
**Pull request by anandmohan4143**
Added input and output to the problem.md

### CODE REVIEW

**Review by Vishruth-S — APPROVED** [review]
Good job 👍 Thanks for contributing 😄

**Comment by Vishruth-S** [comment]
@anandmohan4143  Could you please rename the folder and remove the colon `:` from it. This is an invalid character and will cause error when cloning locally.

Also, you can make the changes and push it within this PR, You don't have to create another one 😅

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Could you please rename the folder and remove the colon `:` from it. This is an invalid character and will cause error when cloning locally.

**Comment by anandmohan4143** [comment]
> @anandmohan4143 Could you please rename the folder and remove the colon `:` from it. This is an invalid character and will cause error when cloning locally.
> 
> Also, you can make the changes and push it within this PR, You don't have to create another one

Sorry. I am new to github. I will try to make change here.

**Review by anandmohan4143 — COMMENTED** [review]
I have renamed the folder name as requested. Please let me know this is fine. Thank you.

**Review by Vishruth-S — APPROVED** [review]
Ok verified 👍  Thanks 😃

**Pull request merged**
