### PR TITLE
some leetcode questions added

### PR DESCRIPTION
**Pull request by shivangigoel1302**

### CODE REVIEW

**Review by Vishruth-S — CHANGES_REQUESTED** [review]
Add comments to your solution explaining the logic used.
This is clearly mentioned [here](https://github.com/Vishruth-S/CompetitiveCode/blob/main/CONTRIBUTING.md#important-note-read-this-before-sending-a-pull-request)

**Comment by Vishruth-S** [comment]
Please reply here if you plan to make the changes or need more time.
The issue will be automatically closed soon if there is no reply

**Comment by shivangigoel1302** [comment]
Will make the changes in a day

**Comment by shivangigoel1302** [comment]
changes has been done do check

**Comment by shivangigoel1302** [comment]
changes have been done . do check

**Review by Vishruth-S — APPROVED** [review]
Good work 👍  
Do star ⭐ this repo if you haven't already 😃

**Pull request merged**
